export component from './component.svg';
export design from './design.svg';
export discord from './discord.svg';
export extension from './extension.svg';
export gitee from './gitee.svg';
export guide from './guide.svg';
export search from './search.svg';
export tools from './tools.svg';
export vsuite from './vsuite.svg';
